Q1. Load the dataset

In [263]:
import pandas as pd

df = pd.read_csv("C:\\Users\\Greesha Vaishnavi\\Downloads\\customer_analytics - customer_analytics.csv")

In [264]:
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 0:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 0:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 0:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 0:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 0:00:00,Yes,Medium,11472.36,124,9.1

Q2. Inspect the end of the dataset

In [265]:
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 0:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 0:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 0:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 0:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 0:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 0:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 0:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 0:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 0:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 0:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

Q3. Random inspection

In [266]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
440,100052,26,111231,193828.85,434,1,Delhi,Premium,Agent,2021-07-09 0:00:00,Yes,High,17552.84,67,2.0
1810,101249,67,133255,233041,493,12,Delhi,Corporate,Online,2023-05-29 0:00:00,No,High,35593.23,93,4.2
265,100745,31,130111,135034.96,786,14,Chennai,Corporate,Online,2023-08-28 0:00:00,Yes,Low,47041.59,93,9.3
1438,100852,20,185400,274577.16,821,12,Pune,Corporate,Agent,2022-05-05 0:00:00,No,Low,10443.1,35,2.8
194,100234,49,207099,238018.2,700,1,NaN,Retail,Online,2026-02-25 0:00:00,yes,Low,37071.96,73,10.0
1103,100804,67,137356,149412.12,822,6,Pune,Premium,Agent,2024-11-26 0:00:00,no,Low,2592.32,68,5.9
1146,100053,56,32314,193935.03,721,5,Delhi,Corporate,Agent,2023-02-18 0:00:00,No,Low,31470.53,50,5.0
214,101931,26,NaN,40706.5,752,14,Hyderabad,NaN,Branch,2025-05-13 0:00:00,No,Low,16101.77,117,4.4
608,101207,21,114489,265374.99,587,6,Pune,Premium,Mobile,2023-06-22 0:00:00,Yes,Medium,6053.97,143,3.8
329,101311,25,92695,147229.5,558,3,Kolkata,SME,Branch,2022-09-22 0:00:00,Yes,Medium,18142.68,131,4.2

Q4. Dataset audit

In [267]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

Q5. Missing-value audit

In [268]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [269]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

Q6. Duplicate investigation

In [270]:
df.duplicated().sum()

np.int64(40)

Q7. Remove duplicates

In [271]:
df = df.drop_duplicates()

In [272]:
df.duplicated().sum()

np.int64(0)

Q8. Numeric column investigation

In [273]:
df.select_dtypes(include='number').columns

Index(['Customer_ID', 'Tenure_Years', 'Satisfaction_Score'], dtype='object')

Q9. Fix Age

In [274]:
df = df.copy()

In [275]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [276]:
age_median = df['Age'].median()

In [277]:
df['Age'] = df['Age'].fillna(age_median)

In [278]:
df['Age'].isna().sum()

np.int64(0)

Q10. Fix Annual Income

In [279]:
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'],errors='coerce')

In [280]:
income_median = df['Annual_Income'].median()

In [281]:
df['Annual_Income'] = df['Annual_Income'].fillna(income_median)

In [282]:
df['Annual_Income'] = df['Annual_Income'].astype(float)

In [283]:
df['Annual_Income'].isna().sum()

np.int64(0)

Q11. Clean Account Balance

In [284]:
df['Account_Balance'] = pd.to_numeric(df['Account_Balance'],errors='coerce')

In [285]:
balance_mean = df['Account_Balance'].mean()

In [286]:
df['Account_Balance'] = df['Account_Balance'].fillna(balance_mean)

In [287]:
df['Account_Balance'].isna().sum()

np.int64(0)

Q12. Clean Credit Score

In [288]:
df['Credit_Score'] = pd.to_numeric(df['Credit_Score'],errors='coerce')

In [289]:
credit_median = df['Credit_Score'].median()

In [290]:
df['Credit_Score'] = df['Credit_Score'].fillna(credit_median)

In [291]:
df['Credit_Score'] = df['Credit_Score'].astype(int)

In [292]:
df['Credit_Score'].isna().sum()

np.int64(0)

Q13. Clean Monthly Spend

In [293]:
df['Monthly_Spend'] = pd.to_numeric(df['Monthly_Spend'],errors='coerce')

In [294]:
spend_median = df['Monthly_Spend'].median()

In [295]:
df['Monthly_Spend'] = df['Monthly_Spend'].fillna(spend_median)

In [296]:
df['Monthly_Spend'].isnull().sum()

np.int64(0)

Q14. Clean Transactions

In [297]:
df['Transactions'] = pd.to_numeric(df['Transactions'],errors='coerce')

In [298]:
transaction_median = df['Transactions'].median()

In [299]:
df['Transactions'] = df['Transactions'].fillna(transaction_median)

In [300]:
df['Transactions'] = df['Transactions'].astype(int)

In [301]:
df['Transactions'].isnull().sum()

np.int64(0)

Q15. Clean Satisfaction Score

In [302]:
df['Satisfaction_Score'] = pd.to_numeric(df['Satisfaction_Score'],errors='coerce')

In [303]:
satisfaction_mean = df['Satisfaction_Score'].mean()

In [304]:
df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(satisfaction_mean)

In [305]:
df['Satisfaction_Score'] = df['Satisfaction_Score'].astype(float)

In [306]:
df['Satisfaction_Score'].isnull().sum()

np.int64(0)

Q16. Investigate Join_Date

In [307]:
df['Join_Date'].head(20)

0     2022-08-15 0:00:00
1     2025-01-11 0:00:00
2     2024-08-01 0:00:00
3     2021-05-15 0:00:00
4     2026-02-03 0:00:00
5     2023-06-04 0:00:00
6     2024-01-16 0:00:00
7     2024-06-26 0:00:00
8     2025-03-12 0:00:00
9     2021-10-07 0:00:00
10    2023-03-02 0:00:00
11    2025-11-22 0:00:00
12    2021-06-25 0:00:00
13    2025-11-19 0:00:00
14    2025-08-26 0:00:00
15    2024-05-05 0:00:00
16    2022-01-07 0:00:00
17    2022-05-25 0:00:00
18    2022-10-07 0:00:00
19    2023-08-10 0:00:00
Name: Join_Date, dtype: object

In [308]:
df['Join_Date'].value_counts()

Join_Date
not_a_date            11
unknown                8
31/99/2024             6
2022-06-26 0:00:00     5
2023-07-19 0:00:00     5
                      ..
2025-12-03 0:00:00     1
2021-01-24 0:00:00     1
2024-08-22 0:00:00     1
2021-03-24 0:00:00     1
2025-04-21 0:00:00     1
Name: count, Length: 1225, dtype: int64

Q17. Convert Join_Date

In [309]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'],errors='coerce')

In [310]:
df['Join_Date'].info()

<class 'pandas.core.series.Series'>
Index: 2000 entries, 0 to 2039
Series name: Join_Date
Non-Null Count  Dtype
--------------  -----
1875 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 31.2 KB

In [311]:
df['Join_Date'].isna().sum()

np.int64(125)

Q18. Handle missing dates

In [312]:
df['Join_Date'].isna().sum()

np.int64(125)

In [313]:
date_median = df['Join_Date'].median()

In [314]:
df['Join_Date'] = df['Join_Date'].fillna(date_median)

In [315]:
df['Join_Date'].isna().sum()

np.int64(0)

Q19. Clean City

In [316]:
df['City'].value_counts()

City
Mumbai       286
Hyderabad    274
Delhi        268
Kolkata      260
Pune         253
Chennai      234
Bangalore    230
mumbai        22
hyderabad     18
bangalore     17
pune          17
delhi         15
kolkata       14
chennai       12
Name: count, dtype: int64

In [317]:
df['City'] = df['City'].replace({
    'mumbai': 'Mumbai',
    'hyderabad': 'Hyderabad',
    'delhi': 'Delhi',
    'pune': 'Pune',
    'chennai': 'Chennai',
    'bangalore': 'Bangalore',
    'kolkata': 'Kolkata'
})

In [318]:
df['City'].value_counts()

City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

Q20. Analyze Segment

In [319]:
df['Segment'].value_counts()

Segment
Premium      516
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

In [320]:
df['Segment'].isna().sum()

np.int64(100)

In [321]:
df['Segment'] = df['Segment'].fillna('Premium')

In [322]:
df['Segment'].value_counts()

Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

Q21. Clean Active

In [323]:
df['Active'] = df['Active'].replace({
    'Y': 'Yes',
    'YES': 'Yes',
    'yes': 'Yes',
    1: 'Yes',
    
    'N': 'No',
    'NO': 'No',
    'no': 'No',
    0: 'No'
})

In [324]:
df['Active'] = df['Active'].fillna('No')

In [325]:
df['Active'].value_counts()

Active
Yes    1333
No      639
0        16
1        12
Name: count, dtype: int64

Q22. Clean Risk_Level

In [326]:
df['Risk_Level'].value_counts()

Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [327]:
df['Risk_Level'].isna().sum()

np.int64(0)

In [328]:
df['Risk_Level'].value_counts()

Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

Q23. Rename columns

In [329]:
df = df.rename(columns={
    'Customer_ID': 'Customer_ID',
    'Annual_Income': 'AnnualIncome',
    'Account_Balance': 'AccountBalance',
    'Credit_Score': 'CreditScore',
    'Tenure_Years': 'Tenure',
    'Join_Date': 'CustomerJoinDate',
    'Risk_Level': 'RiskLevel',
    'Monthly_Spend': 'MonthlySpend',
    'Satisfaction_Score': 'SatisfactionScore'
})

In [330]:
df.columns

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')

Q24. Add prefix

In [331]:
df = df.add_prefix('Customer_')

In [332]:
df.columns

Index(['Customer_Customer_ID', 'Customer_Age', 'Customer_AnnualIncome',
       'Customer_AccountBalance', 'Customer_CreditScore', 'Customer_Tenure',
       'Customer_City', 'Customer_Segment', 'Customer_Channel',
       'Customer_CustomerJoinDate', 'Customer_Active', 'Customer_RiskLevel',
       'Customer_MonthlySpend', 'Customer_Transactions',
       'Customer_SatisfactionScore'],
      dtype='object')

Q25. Remove unnecessary column

In [333]:
df = df.drop('Customer_Customer_ID', axis=1)

In [334]:
df.columns

Index(['Customer_Age', 'Customer_AnnualIncome', 'Customer_AccountBalance',
       'Customer_CreditScore', 'Customer_Tenure', 'Customer_City',
       'Customer_Segment', 'Customer_Channel', 'Customer_CustomerJoinDate',
       'Customer_Active', 'Customer_RiskLevel', 'Customer_MonthlySpend',
       'Customer_Transactions', 'Customer_SatisfactionScore'],
      dtype='object')

Q26. Create Annual Income in Lakhs

In [335]:
df['Income_Lakhs'] = df['Customer_AnnualIncome'] / 100000

In [336]:
df[['Customer_AnnualIncome', 'Income_Lakhs']].head(10)

   Customer_AnnualIncome  Income_Lakhs
0                44033.0       0.44033
1               215546.0       2.15546
2               226403.0       2.26403
3                87824.0       0.87824
4                31570.0       0.31570
5                37087.0       0.37087
6                67229.0       0.67229
7               139914.0       1.39914
8               153267.0       1.53267
9               139914.0       1.39914

Q27. Create Monthly Income

In [337]:
df['MonthlyIncome'] = df['Customer_AnnualIncome'] / 12

In [338]:
df['Income_After_Spending'] = (df['MonthlyIncome'] - df['Customer_MonthlySpend'])

In [339]:
df[
    [
        'Customer_AnnualIncome',
        'MonthlyIncome',
        'Customer_MonthlySpend',
        'Income_After_Spending'
    ]
].head(10)

,Customer_AnnualIncome,MonthlyIncome,Customer_MonthlySpend,Income_After_Spending
0,44033.0,3669.416667,23066.19,-19396.773333
1,215546.0,17962.166667,24625.17,-6663.003333
2,226403.0,18866.916667,28536.34,-9669.423333
3,87824.0,7318.666667,12869.71,-5551.043333
4,31570.0,2630.833333,34163.02,-31532.186667
5,37087.0,3090.583333,15121.16,-12030.576667
6,67229.0,5602.416667,17655.61,-12053.193333
7,139914.0,11659.500000,1720.85,9938.650000
8,153267.0,12772.250000,38043.07,-25270.820000
9,139914.0,11659.500000,11472.36,187.140000

Q28. Create Balance-to-Income Ratio

In [340]:
df['Balance_Income_Ratio'] = (
    df['Customer_AccountBalance'] /
    df['Customer_AnnualIncome']
)

In [341]:
df[
    [
        'Customer_AccountBalance',
        'Customer_AnnualIncome',
        'Balance_Income_Ratio'
    ]
].head(10)

   Customer_AccountBalance  Customer_AnnualIncome  Balance_Income_Ratio
0                111350.85                44033.0              2.528805
1                254378.37               215546.0              1.180158
2                159975.42               226403.0              0.706596
3                295741.60                87824.0              3.367435
4                242423.78                31570.0              7.678929
5                180084.44                37087.0              4.855730
6                 99629.81                67229.0              1.481947
7                 61030.94               139914.0              0.436203
8                221707.97               153267.0              1.446547
9                 41126.84               139914.0              0.293944

Q29. Prepare the ML-ready dataset

In [342]:
import pandas as pd

df = pd.read_csv("C:\\Users\\Greesha Vaishnavi\\Downloads\\customer_analytics - customer_analytics.csv")

In [343]:
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 0:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 0:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 0:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 0:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 0:00:00,Yes,Medium,11472.36,124,9.1

In [344]:
df.tail(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 0:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 0:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 0:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 0:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 0:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [345]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1109,100350,25,104148,299839.87,623,4,Pune,Premium,Agent,2021-08-12 0:00:00,Yes,Medium,14230.1,6,9.0
935,101943,56,74678,292553.99,356,12,Pune,Retail,Agent,2026-02-05 0:00:00,Yes,High,40760.49,37,9.3
1203,101403,25,124134,NaN,613,10,Mumbai,Premium,Mobile,2025-11-16 0:00:00,Yes,Medium,28218.23,51,7.1
750,100032,39,165975,286209.94,343,6,Delhi,Premium,Agent,2023-05-10 0:00:00,No,High,11089.18,41,5.3
458,101019,27,222990,278786.52,580,5,Delhi,Corporate,Online,2024-04-27 0:00:00,Yes,Medium,43182.45,145,NaN
653,100278,22,60488,6608.08,850,2,Bangalore,SME,Online,2022-10-01 0:00:00,No,High,30996.88,48,7.2
686,100381,34,186099,25602.4,837,6,Kolkata,Retail,Branch,2021-12-07 0:00:00,No,Low,1928.47,139,7.8
133,100675,74,70379,missing,400,10,Hyderabad,Retail,Branch,2022-01-25 0:00:00,Yes,High,18239.2,3,9.8
1096,101873,30,235748,116969.92,642,13,Chennai,Retail,Agent,2021-04-14 0:00:00,No,Medium,18134.29,106,4.1
1386,100062,NaN,182364,222294.38,749,10,Chennai,Corporate,Online,2025-02-03 0:00:00,No,Low,17885.37,16,8.8

In [346]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [347]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [348]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [349]:
df.duplicated().sum()

np.int64(40)

In [350]:

df = df.drop_duplicates()

In [351]:
df.duplicated().sum()

np.int64(0)

In [352]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [353]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [354]:
df['Annual_Income'] = pd.to_numeric(
    df['Annual_Income'],
    errors='coerce'
)

In [355]:
df['Annual_Income'] = df['Annual_Income'].fillna(df['Annual_Income'].median())

In [356]:
df['Annual_Income'] = df['Annual_Income'].astype(float)

In [357]:
df['Account_Balance'] = pd.to_numeric(
    df['Account_Balance'],
    errors='coerce')

In [358]:
df['Account_Balance'] = df['Account_Balance'].fillna(
    df['Account_Balance'].mean()
)

In [359]:
df['Credit_Score'] = pd.to_numeric(
    df['Credit_Score'],
    errors='coerce'
)

In [360]:
df['Credit_Score'] = df['Credit_Score'].fillna(
    df['Credit_Score'].median()
)

In [361]:
df['Credit_Score'] = df['Credit_Score'].astype(int)

In [362]:
df['Monthly_Spend'] = pd.to_numeric(
    df['Monthly_Spend'],
    errors='coerce'
)

In [363]:
df['Monthly_Spend'] = df['Monthly_Spend'].fillna(
    df['Monthly_Spend'].median()
)

In [364]:
df['Transactions'] = pd.to_numeric(
    df['Transactions'],
    errors='coerce'
)

In [365]:
df['Transactions'] = df['Transactions'].fillna(
    df['Transactions'].median()
)

In [366]:
df['Transactions'] = df['Transactions'].astype(int)

In [367]:
df['Satisfaction_Score'] = pd.to_numeric(
    df['Satisfaction_Score'],
    errors='coerce'
)

In [368]:
df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(
    df['Satisfaction_Score'].mean()
)

In [369]:
df['Satisfaction_Score'] = df['Satisfaction_Score'].astype(float)

In [370]:
df['Join_Date'] = pd.to_datetime(
    df['Join_Date'],
    errors='coerce'
)

In [371]:
df['Join_Date'] = df['Join_Date'].fillna(
    df['Join_Date'].median()
)

In [372]:
df['City'] = df['City'].replace({
    'mumbai': 'Mumbai',
    'hyderabad': 'Hyderabad',
    'delhi': 'Delhi',
    'pune': 'Pune',
    'chennai': 'Chennai',
    'bangalore': 'Bangalore',
    'kolkata': 'Kolkata'
})

In [373]:
df['Segment'] = df['Segment'].fillna('Premium')

In [374]:
df['Active'] = df['Active'].replace({
    'Y': 'Yes',
    'YES': 'Yes',
    'yes': 'Yes',
    1: 'Yes',
    'N': 'No',
    'NO': 'No',
    'no': 'No',
    0: 'No'
})

In [375]:
df['Active'] = df['Active'].fillna('No')

In [376]:
df = df.rename(columns={
    'Customer_ID': 'Customer_ID',
    'Annual_Income': 'AnnualIncome',
    'Account_Balance': 'AccountBalance',
    'Credit_Score': 'CreditScore',
    'Tenure_Years': 'Tenure',
    'Join_Date': 'CustomerJoinDate',
    'Risk_Level': 'RiskLevel',
    'Monthly_Spend': 'MonthlySpend',
    'Satisfaction_Score': 'SatisfactionScore'
})

In [377]:
df = df.add_prefix('Customer_')

In [378]:
df = df.drop(
    'Customer_Customer_ID',
    axis=1
)

In [379]:
df['Income_Lakhs'] = (
    df['Customer_AnnualIncome'] / 100000
)

In [380]:
df['MonthlyIncome'] = (
    df['Customer_AnnualIncome'] / 12
)

In [381]:
df['Income_After_Spending'] = (
    df['MonthlyIncome'] -
    df['Customer_MonthlySpend']
)

In [382]:
df['Balance_Income_Ratio'] = (
    df['Customer_AccountBalance'] /
    df['Customer_AnnualIncome'].replace(0, pd.NA)
)

In [383]:
df.duplicated().sum()

np.int64(0)

In [384]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Customer_Age                2000 non-null   float64
 1   Customer_AnnualIncome       2000 non-null   float64
 2   Customer_AccountBalance     2000 non-null   float64
 3   Customer_CreditScore        2000 non-null   int64
 4   Customer_Tenure             2000 non-null   int64
 5   Customer_City               1920 non-null   object
 6   Customer_Segment            2000 non-null   object
 7   Customer_Channel            2000 non-null   object
 8   Customer_CustomerJoinDate   2000 non-null   datetime64[ns]
 9   Customer_Active             2000 non-null   object
 10  Customer_RiskLevel          2000 non-null   object
 11  Customer_MonthlySpend       2000 non-null   float64
 12  Customer_Transactions       2000 non-null   int64
 13  Customer_SatisfactionScore  2000 non-null   float64
 14  Income_Lakhs                2000 non-null   float64
 15  MonthlyIncome               2000 non-null   float64
 16  Income_After_Spending       2000 non-null   float64
 17  Balance_Income_Ratio        2000 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(3), object(5)
memory usage: 296.9+ KB

In [385]:
df.describe()

,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_CustomerJoinDate,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,47.006000,138362.001000,151344.558019,576.241500,7.574000,2023-08-23 23:16:47.999999744,24846.208835,75.46050,5.605417,1.383620,11530.166750,-13316.042085,1.495399
min,18.000000,25163.000000,55.960000,300.000000,0.000000,2021-01-01 00:00:00,559.580000,1.00000,1.000000,0.251630,2096.916667,-46902.986667,0.000281
25%,34.000000,88617.000000,83956.797500,434.000000,4.000000,2022-06-10 12:00:00,13115.135000,40.00000,3.600000,0.886170,7384.750000,-24603.837500,0.611383
50%,47.000000,139914.000000,151344.558019,570.000000,8.000000,2023-08-24 00:00:00,24625.170000,76.00000,5.605417,1.399140,11659.500000,-12917.411667,1.102992
75%,61.000000,188465.000000,219656.717500,720.250000,12.000000,2024-11-05 00:00:00,36337.937500,112.00000,7.700000,1.884650,15705.416667,-1793.519167,1.835454
max,75.000000,249977.000000,299914.140000,850.000000,15.000000,2026-03-13 00:00:00,49942.820000,149.00000,10.000000,2.499770,20831.416667,19642.133333,11.427467
std,16.184991,61981.578361,82600.275042,160.930521,4.610548,NaN,13850.626971,42.57714,2.527486,0.619816,5165.131530,14857.128756,1.450448

In [386]:
df['Customer_City'].value_counts()

Customer_City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

In [387]:
df['Customer_Segment'].value_counts()

Customer_Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

In [388]:
df['Customer_Active'].value_counts()

Customer_Active
Yes    1333
No      639
0        16
1        12
Name: count, dtype: int64

In [389]:
df['Customer_RiskLevel'].value_counts()

Customer_RiskLevel
High      986
Low       540
Medium    474
Name: count, dtype: int64

In [390]:
import pandas as pd

# STEP 1 — LOAD

df = pd.read_csv("C:\\Users\\Greesha Vaishnavi\\Downloads\\customer_analytics - customer_analytics.csv")


# STEP 2 — INSPECT

df.head()
df.tail()
df.sample(10)
df.info()


# STEP 3 — MISSING VALUE ANALYSIS

df.isnull().sum()
df.isna().sum()

# STEP 4 — DUPLICATE HANDLING

df.duplicated().sum()

df = df.drop_duplicates()

df.duplicated().sum()


# STEP 5 — NUMERIC CLEANING

# Age
df['Age'] = pd.to_numeric(
    df['Age'],
    errors='coerce'
)

df['Age'] = df['Age'].fillna(
    df['Age'].median()
)


# Annual Income
df['Annual_Income'] = pd.to_numeric(
    df['Annual_Income'],
    errors='coerce'
)

df['Annual_Income'] = df['Annual_Income'].fillna(
    df['Annual_Income'].median()
)

df['Annual_Income'] = df['Annual_Income'].astype(float)


# Account Balance
df['Account_Balance'] = pd.to_numeric(
    df['Account_Balance'],
    errors='coerce'
)

df['Account_Balance'] = df['Account_Balance'].fillna(
    df['Account_Balance'].mean()
)


# Credit Score
df['Credit_Score'] = pd.to_numeric(
    df['Credit_Score'],
    errors='coerce'
)

df['Credit_Score'] = df['Credit_Score'].fillna(
    df['Credit_Score'].median()
)

df['Credit_Score'] = df['Credit_Score'].astype(int)


# Monthly Spend
df['Monthly_Spend'] = pd.to_numeric(
    df['Monthly_Spend'],
    errors='coerce'
)

df['Monthly_Spend'] = df['Monthly_Spend'].fillna(
    df['Monthly_Spend'].median()
)


# Transactions
df['Transactions'] = pd.to_numeric(
    df['Transactions'],
    errors='coerce'
)

df['Transactions'] = df['Transactions'].fillna(
    df['Transactions'].median()
)

df['Transactions'] = df['Transactions'].astype(int)


# Satisfaction Score
df['Satisfaction_Score'] = pd.to_numeric(
    df['Satisfaction_Score'],
    errors='coerce'
)

df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(
    df['Satisfaction_Score'].mean()
)

df['Satisfaction_Score'] = df['Satisfaction_Score'].astype(float)


# STEP 6 — DATE CLEANING

df['Join_Date'] = pd.to_datetime(
    df['Join_Date'],
    errors='coerce'
)

df['Join_Date'] = df['Join_Date'].fillna(
    df['Join_Date'].median()
)


# STEP 7 — CATEGORICAL CLEANING

# City
df['City'] = df['City'].replace({
    'mumbai': 'Mumbai',
    'hyderabad': 'Hyderabad',
    'delhi': 'Delhi',
    'pune': 'Pune',
    'chennai': 'Chennai',
    'bangalore': 'Bangalore',
    'kolkata': 'Kolkata'
})


# Segment
df['Segment'] = df['Segment'].fillna('Premium')


# Channel
df['Channel'].value_counts()


# Active
df['Active'] = df['Active'].replace({
    'Y': 'Yes',
    'YES': 'Yes',
    'yes': 'Yes',
    1: 'Yes',
    'N': 'No',
    'NO': 'No',
    'no': 'No',
    0: 'No'
})

df['Active'] = df['Active'].fillna('No')


# Risk Level
df['Risk_Level'].value_counts()


# STEP 8 — COLUMN TRANSFORMATION

df = df.rename(columns={
    'Customer_ID': 'Customer_ID',
    'Annual_Income': 'AnnualIncome',
    'Account_Balance': 'AccountBalance',
    'Credit_Score': 'CreditScore',
    'Tenure_Years': 'Tenure',
    'Join_Date': 'CustomerJoinDate',
    'Risk_Level': 'RiskLevel',
    'Monthly_Spend': 'MonthlySpend',
    'Satisfaction_Score': 'SatisfactionScore'
})


df = df.add_prefix('Customer_')


df = df.drop(
    'Customer_Customer_ID',
    axis=1
)

# STEP 9 — ANALYTICAL FEATURES

df['Income_Lakhs'] = (
    df['Customer_AnnualIncome'] / 100000
)

df['MonthlyIncome'] = (
    df['Customer_AnnualIncome'] / 12
)

df['Income_After_Spending'] = (
    df['MonthlyIncome'] -
    df['Customer_MonthlySpend']
)

df['Balance_Income_Ratio'] = (
    df['Customer_AccountBalance'] /
    df['Customer_AnnualIncome'].replace(0, pd.NA)
)

df['Customer_City'] = df['Customer_City'].fillna('Unknown')

df['Customer_Active'] = df['Customer_Active'].replace({
    1: 'Yes',
    0: 'No',
    '1': 'Yes',
    '0': 'No'
})


df['Customer_City'].isna().sum()

df['Customer_Active'].value_counts()

# STEP 10 — FINAL VALIDATION

# Duplicate check
print("Duplicates:")
print(df.duplicated().sum())


# Datatypes
print("\nDatatypes:")
print(df.dtypes)


# Missing values
print("\nMissing Values:")
print(df.isnull().sum())


# Numeric statistics
print("\nDescriptive Statistics:")
print(df.describe())


# Categorical distributions
print("\nCity:")
print(df['Customer_City'].value_counts())


print("\nSegment:")
print(df['Customer_Segment'].value_counts())


print("\nChannel:")
print(df['Customer_Channel'].value_counts())


print("\nActive:")
print(df['Customer_Active'].value_counts())


print("\nRisk Level:")
print(df['Customer_RiskLevel'].value_counts())


# Final inspection
print("\nFirst 10 rows:")
print(df.head(10))

print("\nLast 10 rows:")
print(df.tail(10))

print("\nRandom 10 rows:")
print(df.sample(10))

print("\nFinal Information:")
df.info()

df['Customer_City'] = df['Customer_City'].fillna('Unknown')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB
Duplicates:
0

Datatypes:
Customer_Age                         float64
Customer_AnnualIncome                float64
Customer_AccountBalance              float64
Customer_CreditScore                   int64
Customer_Tenure                        int64
Customer_City                         object
Customer_Segment                      object
Customer_Channel                      object
Customer_CustomerJoinDate     datetime64[ns]
Customer_Active                       object
Customer_RiskLevel                    object
Customer_MonthlySpend                float64
Customer_Transactions                  int64
Customer_SatisfactionScore           float64
Income_Lakhs                         float64
MonthlyIncome                        float64
Income_After_Spending                float64
Balance_Income_Ratio                 float64
dtype: object

Missing Values:
Customer_Age                  0
Customer_AnnualIncome         0
Customer_AccountBalance       0
Customer_CreditScore          0
Customer_Tenure               0
Customer_City                 0
Customer_Segment              0
Customer_Channel              0
Customer_CustomerJoinDate     0
Customer_Active               0
Customer_RiskLevel            0
Customer_MonthlySpend         0
Customer_Transactions         0
Customer_SatisfactionScore    0
Income_Lakhs                  0
MonthlyIncome                 0
Income_After_Spending         0
Balance_Income_Ratio          0
dtype: int64

Descriptive Statistics:
       Customer_Age  Customer_AnnualIncome  Customer_AccountBalance  \
count   2000.000000            2000.000000              2000.000000
mean      47.006000          138362.001000            151344.558019
min       18.000000           25163.000000                55.960000
25%       34.000000           88617.000000             83956.797500
50%       47.000000          139914.000000            151344.558019
75%       61.000000          188465.000000            219656.717500
max       75.000000          249977.000000            299914.140000
std       16.184991           61981.578361             82600.275042

       Customer_CreditScore  Customer_Tenure      Customer_CustomerJoinDate  \
count           2000.000000      2000.000000                           2000
mean             576.241500         7.574000  2023-08-23 23:16:47.999999744
min              300.000000         0.000000            2021-01-01 00:00:00
25%              434.000000         4.000000            2022-06-10 12:00:00
50%              570.000000         8.000000            2023-08-24 00:00:00
75%              720.250000        12.000000            2024-11-05 00:00:00
max              850.000000        15.000000            2026-03-13 00:00:00
std              160.930521         4.610548                            NaN

       Customer_MonthlySpend  Customer_Transactions  \
count            2000.000000             2000.00000
mean            24846.208835               75.46050
min               559.580000                1.00000
25%             13115.135000               40.00000
50%             24625.170000               76.00000
75%             36337.937500              112.00000
max             49942.820000              149.00000
std             13850.626971               42.57714

       Customer_SatisfactionScore  Income_Lakhs  MonthlyIncome  \
count                 2000.000000   2000.000000    2000.000000
mean                     5.605417      1.383620   11530.166750
min                      1.000000      0.251630    2096.916667
25%                      3.600000      0.886170    7384.750000
50%                      5.605417      1.399140   11659.500000
75%                      7.700000      1.884650   15705.416667
max                     10.000000      2.499770   20831.416667
std                      2.527486      0.619816    5165.131530

       Income_After_Spending  Balance_Income_Ratio
count            2000.000000           2000.000000
mean           -13316.042085              1.495399
min            -46902.986667              0.000281
25%            -24603.837500              0.611383
50%            -12917.411667              1.102992
75%             -1793.519167              1.835454
max             19642.133333             11.427467
std             14857.128756              1.450448

City:
Customer_City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Unknown       80
Name: count, dtype: int64

Segment:
Customer_Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

Channel:
Customer_Channel
Agent     530
Online    497
Branch    493
Mobile    480
Name: count, dtype: int64

Active:
Customer_Active
Yes    1345
No      655
Name: count, dtype: int64

Risk Level:
Customer_RiskLevel
High      986
Low       540
Medium    474
Name: count, dtype: int64

First 10 rows:
   Customer_Age  Customer_AnnualIncome  Customer_AccountBalance  \
0          55.0                44033.0                111350.85
1          32.0               215546.0                254378.37
2          23.0               226403.0                159975.42
3          66.0                87824.0                295741.60
4          67.0                31570.0                242423.78
5          68.0                37087.0                180084.44
6          47.0                67229.0                 99629.81
7          65.0               139914.0                 61030.94
8          63.0               153267.0                221707.97
9          42.0               139914.0                 41126.84

   Customer_CreditScore  Customer_Tenure Customer_City Customer_Segment  \
0                   772                3     Bangalore              SME
1                   374                8         Delhi           Retail
2                   668               12       Chennai          Premium
3                   315               14        Mumbai          Premium
4                   370                4     Bangalore           Retail
5                   738                1       Chennai          Premium
6                   464                4       Chennai           Retail
7                   554               15       Kolkata              SME
8                   508                5     Hyderabad          Premium
9                   556                3       Kolkata        Corporate

  Customer_Channel Customer_CustomerJoinDate Customer_Active  \
0            Agent                2022-08-15             Yes
1            Agent                2025-01-11             Yes
2            Agent                2024-08-01              No
3            Agent                2021-05-15             Yes
4            Agent                2026-02-03              No
5            Agent                2023-06-04             Yes
6           Online                2024-01-16             Yes
7            Agent                2024-06-26             Yes
8           Mobile                2025-03-12             Yes
9           Mobile                2021-10-07             Yes

  Customer_RiskLevel  Customer_MonthlySpend  Customer_Transactions  \
0                Low               23066.19                    135
1               High               24625.17                    106
2             Medium               28536.34                    146
3               High               12869.71                    115
4               High               34163.02                     94
5                Low               15121.16                      6
6               High               17655.61                     31
7             Medium                1720.85                    139
8               High               38043.07                     76
9             Medium               11472.36                    124

   Customer_SatisfactionScore  Income_Lakhs  MonthlyIncome  \
0                         3.1       0.44033    3669.416667
1                         8.2       2.15546   17962.166667
2                         6.3       2.26403   18866.916667
3                         9.7       0.87824    7318.666667
4                         3.7       0.31570    2630.833333
5                         8.5       0.37087    3090.583333
6                         2.8       0.67229    5602.416667
7                         9.7       1.39914   11659.500000
8                         7.1       1.53267   12772.250000
9                         9.1       1.39914   11659.500000

   Income_After_Spending  Balance_Income_Ratio
0          -19396.773333              2.528805
1           -6663.003333              1.180158
2           -9669.423333              0.706596
3           -5551.043333              3.367435
4          -31532.186667              7.678929
5          -12030.576667              4.855730
6          -12053.193333              1.481947
7            9938.650000              0.436203
8          -25270.820000              1.446547
9             187.140000              0.293944

Last 10 rows:
      Customer_Age  Customer_AnnualIncome  Customer_AccountBalance  \
2030          41.0               201611.0                 40736.71
2031          61.0               128850.0                266135.80
2032          33.0                88037.0                129948.93
2033          43.0               122756.0                 36633.45
2034          18.0               189232.0                235131.72
2035          42.0                88530.0                153490.72
2036          31.0               205738.0                270989.40
2037          25.0               211994.0                160507.65
2038          64.0                30105.0                 32117.15
2039          55.0               248332.0                274980.99

      Customer_CreditScore  Customer_Tenure Customer_City Customer_Segment  \
2030                   507               15     Bangalore              SME
2031                   840                9       Kolkata              SME
2032                   449                8        Mumbai          Premium
2033                   487                8          Pune          Premium
2034                   306               10     Hyderabad              SME
2035                   677               12     Hyderabad           Retail
2036                   392                8        Mumbai        Corporate
2037                   737                8       Kolkata           Retail
2038                   794                8     Bangalore           Retail
2039                   783                6       Chennai           Retail

     Customer_Channel Customer_CustomerJoinDate Customer_Active  \
2030            Agent                2024-11-03             Yes
2031           Mobile                2026-01-15             Yes
2032           Mobile                2022-11-30             Yes
2033           Mobile                2021-07-04              No
2034           Mobile                2025-09-10              No
2035            Agent                2021-07-10              No
2036            Agent                2025-07-05             Yes
2037           Online                2022-10-17             Yes
2038            Agent                2023-08-26              No
2039           Branch                2023-08-24             Yes

     Customer_RiskLevel  Customer_MonthlySpend  Customer_Transactions  \
2030               High               18815.18                     58
2031                Low               34300.44                     83
2032               High               24625.17                    147
2033               High               10165.71                     14
2034               High               27227.44                     85
2035             Medium                8455.42                    119
2036               High               34087.69                    134
2037                Low               26518.74                     87
2038                Low               20943.11                    107
2039                Low               48511.32                    119

      Customer_SatisfactionScore  Income_Lakhs  MonthlyIncome  \
2030                         7.2       2.01611   16800.916667
2031                         5.0       1.28850   10737.500000
2032                         9.7       0.88037    7336.416667
2033                         6.4       1.22756   10229.666667
2034                         5.9       1.89232   15769.333333
2035                         8.6       0.88530    7377.500000
2036                         2.6       2.05738   17144.833333
2037                         1.3       2.11994   17666.166667
2038                         9.3       0.30105    2508.750000
2039                         3.1       2.48332   20694.333333

      Income_After_Spending  Balance_Income_Ratio
2030           -2014.263333              0.202056
2031          -23562.940000              2.065470
2032          -17288.753333              1.476072
2033              63.956667              0.298425
2034          -11458.106667              1.242558
2035           -1077.920000              1.733771
2036          -16942.856667              1.317158
2037           -8852.573333              0.757133
2038          -18434.360000              1.066838
2039          -27816.986667              1.107312

Random 10 rows:
      Customer_Age  Customer_AnnualIncome  Customer_AccountBalance  \
2006          24.0                34596.0             79611.030000
558           59.0               145585.0            207028.970000
1844          31.0               222744.0            157743.780000
1631          65.0               147720.0             64388.420000
1404          34.0               105532.0            206933.650000
1984          71.0               175273.0            179128.730000
307           47.0               139914.0             33018.990000
1871          74.0                38140.0            151344.558019
1163          66.0               182661.0            210010.280000
642           55.0               204967.0             93300.750000

      Customer_CreditScore  Customer_Tenure Customer_City Customer_Segment  \
2006                   695                1       Chennai          Premium
558                    393                3       Chennai          Premium
1844                   648                5     Hyderabad              SME
1631                   628                7     Bangalore        Corporate
1404                   758                6          Pune              SME
1984                   815                2     Hyderabad           Retail
307                    354               13       Kolkata        Corporate
1871                   693                7       Kolkata          Premium
1163                   830                2         Delhi              SME
642                    713                8          Pune          Premium

     Customer_Channel Customer_CustomerJoinDate Customer_Active  \
2006            Agent                2022-05-28              No
558             Agent                2022-09-07             Yes
1844            Agent                2023-01-18             Yes
1631           Online                2026-01-17              No
1404           Online                2025-03-19             Yes
1984            Agent                2026-02-01             Yes
307            Mobile                2021-09-02             Yes
1871           Mobile                2024-07-07             Yes
1163           Branch                2025-12-04             Yes
642             Agent                2024-09-19             Yes

     Customer_RiskLevel  Customer_MonthlySpend  Customer_Transactions  \
2006             Medium                 973.13                    112
558                High                4079.37                     80
1844             Medium                8217.97                    116
1631             Medium                7896.88                    129
1404                Low               32046.59                     71
1984                Low               24457.54                     98
307                High                6517.05                     98
1871             Medium               12735.15                    122
1163                Low               42083.82                     45
642                 Low               47767.94                    138

      Customer_SatisfactionScore  Income_Lakhs  MonthlyIncome  \
2006                    1.000000       0.34596    2883.000000
558                     7.300000       1.45585   12132.083333
1844                    1.700000       2.22744   18562.000000
1631                    1.500000       1.47720   12310.000000
1404                    1.500000       1.05532    8794.333333
1984                    8.500000       1.75273   14606.083333
307                     7.900000       1.39914   11659.500000
1871                    5.605417       0.38140    3178.333333
1163                    8.200000       1.82661   15221.750000
642                     9.100000       2.04967   17080.583333

      Income_After_Spending  Balance_Income_Ratio
2006            1909.870000              2.301163
558             8052.713333              1.422049
1844           10344.030000              0.708184
1631            4413.120000              0.435882
1404          -23252.256667              1.960862
1984           -9851.456667              1.021998
307             5142.450000              0.235995
1871           -9556.816667              3.968132
1163          -26862.070000              1.149727
642           -30687.356667              0.455199

Final Information:
<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Customer_Age                2000 non-null   float64
 1   Customer_AnnualIncome       2000 non-null   float64
 2   Customer_AccountBalance     2000 non-null   float64
 3   Customer_CreditScore        2000 non-null   int64
 4   Customer_Tenure             2000 non-null   int64
 5   Customer_City               2000 non-null   object
 6   Customer_Segment            2000 non-null   object
 7   Customer_Channel            2000 non-null   object
 8   Customer_CustomerJoinDate   2000 non-null   datetime64[ns]
 9   Customer_Active             2000 non-null   object
 10  Customer_RiskLevel          2000 non-null   object
 11  Customer_MonthlySpend       2000 non-null   float64
 12  Customer_Transactions       2000 non-null   int64
 13  Customer_SatisfactionScore  2000 non-null   float64
 14  Income_Lakhs                2000 non-null   float64
 15  MonthlyIncome               2000 non-null   float64
 16  Income_After_Spending       2000 non-null   float64
 17  Balance_Income_Ratio        2000 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(3), object(5)
memory usage: 296.9+ KB

In [391]:
df.to_csv("cleaned_customer_analytics.csv", index=False)